# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

City.find_or_create_by(name: 'Santiago')
City.find_or_create_by(name: 'Concepción')
City.find_or_create_by(name: 'Valparaíso')
City.find_or_create_by(name: 'La Serena')
City.find_or_create_by(name: 'Temuco')
City.find_or_create_by(name: 'Antofagasta')
City.find_or_create_by(name: 'Iquique')
City.find_or_create_by(name: 'Rancagua')
City.find_or_create_by(name: 'Puerto Montt')
City.find_or_create_by(name: 'Talca')
City.find_or_create_by(name: 'Arica')
City.find_or_create_by(name: 'Chillán')
City.find_or_create_by(name: 'Los Ángeles')
City.find_or_create_by(name: 'Quillota')
City.find_or_create_by(name: 'Valdivia')
City.find_or_create_by(name: 'Osorno')
City.find_or_create_by(name: 'San Antonio')
City.find_or_create_by(name: 'Curicó')
City.find_or_create_by(name: 'Calama')
City.find_or_create_by(name: 'Punta Arenas')
City.find_or_create_by(name: 'Colina')
City.find_or_create_by(name: 'Melipilla')
City.find_or_create_by(name: 'Ovalle')
City.find_or_create_by(name: 'Linares')
City.find_or_create_by(name: 'Peñaflos')
City.find_or_create_by(name: 'Lampa')
City.find_or_create_by(name: 'Buin')
City.find_or_create_by(name: 'San Fernando')
City.find_or_create_by(name: 'San Felipe')
City.find_or_create_by(name: 'Paine')
City.find_or_create_by(name: 'Talagante')
City.find_or_create_by(name: 'Los Andes')
City.find_or_create_by(name: 'Coyhaique')
City.find_or_create_by(name: 'Rengo')
City.find_or_create_by(name: 'Vallenar')
City.find_or_create_by(name: 'Villarica')
City.find_or_create_by(name: 'San Carlos')
City.find_or_create_by(name: 'Angol')
City.find_or_create_by(name: 'Other')

city_id = City.first.id

Raider.find_or_create_by(name:'Steven', lastName:'Hawkins', rut:'162832999', acceptedTerms:true, birthdate: "01-01-1980", email: "example@example.com", city_id: city_id)
Raider.find_or_create_by(name:'Mike', lastName:'Charlain', rut:'174043124', acceptedTerms:true, birthdate: "01-01-1980", email: "example@example.com", city_id: city_id)
Raider.find_or_create_by(name:'Stiff', lastName:'Fitzer', rut:'60532494', acceptedTerms:true, birthdate: "01-01-1980", email: "example@example.com", city_id: city_id)
